### ISSUE TITLE
definitions.json

### ISSUE THREAD

**Issue by ne0dym7** [Soreepeong/XivMitmLatencyMitigator#22]
I'm opening a new thread so as to not clog the one in the XivAlexander page, hopefully that's ok. You and someone else suggested deleting the definitions.json file in order to update the opcodes, but I'm afraid I have no idea where to find that file!
What I've been doing is run the iptables and curl commands on virtualbox every time I launch the game on my PS4. My laptop running the VM has to be running at all times since pressing Ctrl+C to exit the program just makes my game disconnect, and when I'm done for the day I can just pause the VM and put the PC to sleep.
Idk if that is the intended way to run the program but that's what has worked for me. Could you perhaps point me to where that file would be stored, or the correct way to use the program? Thanks so much for your work

**Comment by Rappy28** [comment]
I'm using the program the same way as you, only I actually quit the VM every time due to memory concerns, I've found my VM to get laggy after a while if I don't reboot it (or reboot the whole computer).

You can delete the JSON file by first running `iptables` and `curl` as you normally would, quit the program with Ctrl+C, then enter the line of code `rm definitions.json`. Then run the program again.

This worked for me today a few hours ago, though to be honest with you I cannot say if that is because I did something right, or something was updated.
