### ISSUE TITLE
No longer working after 6.25

### ISSUE THREAD

**Issue by tsugako** [Soreepeong/XivMitmLatencyMitigator#65]
the program closes the connection after an action in game.
![unknown](https://user-images.githubusercontent.com/116118261/196537509-07560636-7b26-4848-886c-0e59c208a769.png)

**Comment by quoehhh** [comment]
hi there! you need to wait for the developer to update their opcodes.
If you're like me who can't wait, you can use the xivalexander and get the latest opcodes instead. 
the guide on getting the latest opcodes is also found on xivalexander github page.

**Comment by Arkzera** [comment]
> hi there! you need to wait for the developer to update their opcodes. If you're like me who can't wait, you can use the xivalexander and get the latest opcodes instead. the guide on getting the latest opcodes is also found on xivalexander github page.

how u change it manually?

**Comment by quoehhh** [comment]
you need to edit the definitions.json file.
If you're using JP region here are the opcodes i got to made it work.

{"C2S_ActionRequest": "0x0140", "C2S_ActionRequestGroundTargeted": "0x0140", "S2C_ActionEffect01": "0x03c4", "S2C_ActionEffect08": "0x0391", "S2C_ActionEffect16": "0x0391", "S2C_ActionEffect24": "0x0391", "S2C_ActionEffect32": "0x0391", "S2C_ActorCast": "0x02ec", "S2C_ActorControl": "0x039e", "S2C_ActorControlSelf": "0x03ce", "Server_IpRange": "124.150.157.0/24, 153.254.80.0/24, 202.67.52.0/24, 204.2.229.0/24, 80.239.145.0/24", "Server_PortRange": "1025-65535", "Name": "game.JP.2022.09.07.0000.0000.json"}

Note: (The opcodes for targetting 9 or more targets are not updated since im lazy to find mobs xD)
But this should work if you are just hitting 1-8 targets. You can just wait for our hardworking developers to update their opcodes.

**Comment by Arkzera** [comment]
> you need to edit the definitions.json file. If you're using JP region here are the opcodes i got to made it work.
> 
> {"C2S_ActionRequest": "0x0140", "C2S_ActionRequestGroundTargeted": "0x0140", "S2C_ActionEffect01": "0x03c4", "S2C_ActionEffect08": "0x0391", "S2C_ActionEffect16": "0x0391", "S2C_ActionEffect24": "0x0391", "S2C_ActionEffect32": "0x0391", "S2C_ActorCast": "0x02ec", "S2C_ActorControl": "0x039e", "S2C_ActorControlSelf": "0x03ce", "Server_IpRange": "124.150.157.0/24, 153.254.80.0/24, 202.67.52.0/24, 204.2.229.0/24, 80.239.145.0/24", "Server_PortRange": "1025-65535", "Name": "game.JP.2022.09.07.0000.0000.json"}
> 
> Note: (The opcodes for targetting 9 or more targets are not updated since im lazy to find mobs xD) But this should work if you are just hitting 1-8 targets. You can just wait for our hardworking developers to update their opcodes.

it can be edited using the terminal? if so, how? Thanks in advance, rly appreciate your help

**Comment by quoehhh** [comment]
you can use vim or nano to edit files on linux.
Hey it's always a good time to learn linux isn't it?

**Comment by tsugako** [comment]
> hi there! you need to wait for the developer to update their opcodes. If you're like me who can't wait, you can use the xivalexander and get the latest opcodes instead. the guide on getting the latest opcodes is also found on xivalexander github page.

Okay, ty

**Comment by RayLynx** [comment]
same issue here
PS5 c.c

**Comment by DiegoSalazar231** [comment]
o/  where did you find definitions.json? It´s such a dumb question, I know lmao

**Comment by DiegoSalazar231** [comment]
> I've just updated the data source; try deleting the file and restarting this script.

Thanks, man. You are truly a hero for many of us, it works :D
